-- ==========================================================
-- add_50_featured_movies.sql
-- Adds 50 NEW movies (does not touch or delete any existing
-- movies) and marks them is_featured = 1, so they show up in
-- the Featured section right after whatever is already there.
-- 25 Hollywood + 25 Bollywood, spread across all 10 genres
-- (5 movies per genre). Titles & descriptions are original /
-- fictional -- no copyright issues.
-- Run this on your existing movie_booking database.
-- ==========================================================

INSERT INTO `movies`
(`title`, `genre`, `language`, `industry`, `quality_tag`, `duration_minutes`, `description`, `trailer_url`, `poster`, `release_date`, `is_featured`, `created_at`)
VALUES
('Nightfall', 'Horror', 'English', 'Hollywood', '2K', 100, 'Something follows June Reyes home from an abandoned house on the edge of Phoenix, and as strange occurrences escalate, Wesley Reyes realizes the danger isn''t in the house anymore, it''s already inside with them.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Nightfall', '2027-02-28', 1, NOW()),
('Between Us Udaipur', 'Drama', 'Urdu', 'Bollywood', 'HD', 129, 'After a family secret comes undone in Udaipur, Ishita Mehra must decide whether protecting Kavya Oberoi is worth the truth they have both been avoiding for years.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Between%20Us%20Udaipur', '2026-09-24', 1, NOW()),
('Still Portland', 'Romance', 'English', 'Hollywood', '2K', 102, 'Years after a breakup no one really explained, Reese Harmon runs into Marcus Whitfield again in Portland, and old feelings resurface at exactly the wrong, and maybe the right, time.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Still%20Portland', '2026-06-13', 1, NOW()),
('Nova Varanasi', 'Sci-Fi', 'Urdu', 'Bollywood', '4K', 113, 'Dev Kapoor wakes up in a Varanasi that remembers a different version of history, and must work with Rudra Chatterjee to figure out which timeline is real before the correction finishes erasing them both.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Nova%20Varanasi', '2026-04-24', 1, NOW()),
('Blackout Baltimore', 'Action', 'English', 'Hollywood', 'IMAX', 160, 'When a black-market deal collapses in Baltimore, June Marsh is the only one standing between a rogue cell and a shipment that could tip a fragile ceasefire. Hunted by former allies, June Marsh has one night to finish what Cole Vance started.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Blackout%20Baltimore', '2026-01-28', 1, NOW()),
('Moonlit Shimla', 'Animation', 'Urdu', 'Bollywood', '4K', 162, 'When the lights of Shimla start disappearing one by one, a curious young inventor named Kavya Chauhan teams up with Anaya Bhatt to find out who, or what, is behind it.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Moonlit%20Shimla', '2026-11-24', 1, NOW()),
('Nightfall Portland', 'Horror', 'English', 'Hollywood', 'HD', 153, 'Something follows Ivy Ellery home from an abandoned house on the edge of Portland, and as strange occurrences escalate, June Cross realizes the danger isn''t in the house anymore, it''s already inside with them.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Nightfall%20Portland', '2027-09-25', 1, NOW()),
('Drift', 'Adventure', 'Urdu', 'Bollywood', '2K', 142, 'A weathered guide named Anaya Deshmukh agrees to lead Kavya Mehra across the forgotten trails beyond Shimla in search of a relic that vanished generations ago, unaware that the journey will cost them everything they thought they knew about home.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Drift', '2026-10-11', 1, NOW()),
('Nightfall Austin', 'Horror', 'English', 'Hollywood', 'IMAX', 105, 'Something follows Delia Sutton home from an abandoned house on the edge of Austin, and as strange occurrences escalate, Ivy Rourke realizes the danger isn''t in the house anymore, it''s already inside with them.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Nightfall%20Austin', '2026-09-25', 1, NOW()),
('After the Rain', 'Romance', 'Urdu', 'Bollywood', 'IMAX', 134, 'Vikram Chauhan and Diya Deshmukh meet by accident on a rainy evening in Lucknow, and what begins as a passing conversation slowly turns into the kind of love neither of them was looking for, or ready to walk away from.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=After%20the%20Rain', '2027-08-17', 1, NOW()),
('The Wedding', 'Comedy', 'English', 'Hollywood', 'HD', 123, 'When Marcus Reyes accidentally becomes the face of a failing local business in Boston, chaos, and an unlikely friendship with Reese Thorne, follow at every turn.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=The%20Wedding', '2026-12-21', 1, NOW()),
('Home Again Amritsar', 'Drama', 'Hindi', 'Bollywood', '2K', 122, 'Meera Rathore returns to Amritsar for a funeral and ends up confronting Rohan Malhotra about the choices that quietly pulled their family apart, one conversation at a time.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Home%20Again%20Amritsar', '2027-04-26', 1, NOW()),
('Echo Boston', 'Sci-Fi', 'English', 'Hollywood', 'HD', 154, 'Delia Cross wakes up in a Boston that remembers a different version of history, and must work with Talia Thorne to figure out which timeline is real before the correction finishes erasing them both.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Echo%20Boston', '2026-01-13', 1, NOW()),
('Redline Reborn', 'Action', 'Hindi', 'Bollywood', '2K', 154, 'Aditya Bhatt, a disgraced officer exiled to the edges of Chandigarh, is pulled back into action when Kavya Rathore is taken hostage during a botched raid. What starts as a rescue turns into a reckoning with the syndicate Aditya Bhatt once worked for.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Redline%20Reborn', '2026-08-26', 1, NOW()),
('No Witness Rising', 'Thriller', 'English', 'Hollywood', 'IMAX', 116, 'June Reyes starts receiving messages that only someone watching very closely could send, and as the city of Phoenix closes in, Mia Ellery becomes the only person left to trust, or the one person who cannot be trusted at all.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=No%20Witness%20Rising', '2027-08-07', 1, NOW()),
('Blind Spot Mumbai', 'Thriller', 'Urdu', 'Bollywood', '2K', 114, 'A routine assignment turns dangerous when Kabir Malhotra uncovers evidence that implicates Anaya Oberoi, forcing a race across Mumbai before the truth gets buried for good.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Blind%20Spot%20Mumbai', '2027-04-02', 1, NOW()),
('Signal San Diego', 'Sci-Fi', 'English', 'Hollywood', '2K', 159, 'Roman Vance wakes up in a San Diego that remembers a different version of history, and must work with June Sutton to figure out which timeline is real before the correction finishes erasing them both.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Signal%20San%20Diego', '2026-09-03', 1, NOW()),
('What Remains Rising', 'Drama', 'Hindi', 'Bollywood', 'HD', 100, 'After a family secret comes undone in Shimla, Anaya Kapoor must decide whether protecting Priya Kapoor is worth the truth they have both been avoiding for years.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=What%20Remains%20Rising', '2027-11-19', 1, NOW()),
('The Setup Portland', 'Thriller', 'English', 'Hollywood', '4K', 111, 'A routine assignment turns dangerous when Roman Marsh uncovers evidence that implicates Grant Rourke, forcing a race across Portland before the truth gets buried for good.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=The%20Setup%20Portland', '2027-06-25', 1, NOW()),
('Zero Pune', 'Action', 'Hindi', 'Bollywood', '4K', 111, 'Rohan Malhotra, a disgraced officer exiled to the edges of Pune, is pulled back into action when Aryan Chatterjee is taken hostage during a botched raid. What starts as a rescue turns into a reckoning with the syndicate Rohan Malhotra once worked for.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Zero%20Pune', '2026-04-12', 1, NOW()),
('Last Score Phoenix', 'Crime', 'English', 'Hollywood', '2K', 108, 'Detective Sienna Harmon is pulled back to Phoenix to close a case that was never really closed, only to find Marcus Faulkner at the center of it all along.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Last%20Score%20Phoenix', '2027-02-04', 1, NOW()),
('Still Pune', 'Romance', 'Hindi', 'Bollywood', 'IMAX', 159, 'Years after a breakup no one really explained, Zara Chauhan runs into Dev Sinha again in Pune, and old feelings resurface at exactly the wrong, and maybe the right, time.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Still%20Pune', '2027-01-03', 1, NOW()),
('The Wedding Reborn', 'Comedy', 'English', 'Hollywood', 'IMAX', 115, 'Talia Faulkner promises to help Cole Sutton pull off the wedding of the century in Chicago; naturally, absolutely nothing goes according to plan.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=The%20Wedding%20Reborn', '2027-09-01', 1, NOW()),
('Moonlit Mumbai', 'Animation', 'Urdu', 'Bollywood', '4K', 100, 'In a vividly imagined version of Mumbai, a small, determined creature named Kavya Kapoor sets out to save its shrinking home, with the reluctant help of a wandering wanderer voiced by the spirit of Vikram Deshmukh.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Moonlit%20Mumbai', '2027-01-12', 1, NOW()),
('Last Score', 'Crime', 'English', 'Hollywood', '2K', 114, 'Detective Owen Ellery is pulled back to Boston to close a case that was never really closed, only to find Reese Ellery at the center of it all along.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Last%20Score', '2026-03-14', 1, NOW()),
('Total Chaos at', 'Comedy', 'Hindi', 'Bollywood', '2K', 123, 'Arjun Chauhan promises to help Aditya Bhatt pull off the wedding of the century in Kolkata; naturally, absolutely nothing goes according to plan.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Total%20Chaos%20at', '2027-06-10', 1, NOW()),
('The Other Room Denver', 'Horror', 'English', 'Hollywood', '4K', 130, 'Something follows Reese Thorne home from an abandoned house on the edge of Denver, and as strange occurrences escalate, Blake Ellery realizes the danger isn''t in the house anymore, it''s already inside with them.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=The%20Other%20Room%20Denver', '2027-11-27', 1, NOW()),
('Home Again Udaipur', 'Drama', 'Hindi', 'Bollywood', '4K', 139, 'Zara Bajwa returns to Udaipur for a funeral and ends up confronting Arjun Kapoor about the choices that quietly pulled their family apart, one conversation at a time.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Home%20Again%20Udaipur', '2027-10-17', 1, NOW()),
('Unspoken Portland', 'Drama', 'English', 'Hollywood', 'IMAX', 141, 'After a family secret comes undone in Portland, Ivy Whitfield must decide whether protecting Roman Thorne is worth the truth they have both been avoiding for years.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Unspoken%20Portland', '2026-11-11', 1, NOW()),
('The Job', 'Crime', 'Urdu', 'Bollywood', '2K', 165, 'Detective Priya Bajwa is pulled back to Udaipur to close a case that was never really closed, only to find Kavya Rana at the center of it all along.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=The%20Job', '2026-07-22', 1, NOW()),
('Adventures in', 'Animation', 'English', 'Hollywood', '4K', 133, 'In a vividly imagined version of Baltimore, a small, determined creature named Wesley Ellery sets out to save its shrinking home, with the reluctant help of a wandering wanderer voiced by the spirit of Piper Doyle.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Adventures%20in', '2026-07-26', 1, NOW()),
('The Setup', 'Thriller', 'Urdu', 'Bollywood', '4K', 105, 'Karan Chatterjee starts receiving messages that only someone watching very closely could send, and as the city of Goa closes in, Aditya Ahluwalia becomes the only person left to trust, or the one person who cannot be trusted at all.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=The%20Setup', '2027-02-27', 1, NOW()),
('My Big Denver', 'Comedy', 'English', 'Hollywood', 'IMAX', 104, 'Reese Ellery promises to help Sienna Thorne pull off the wedding of the century in Denver; naturally, absolutely nothing goes according to plan.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=My%20Big%20Denver', '2027-11-19', 1, NOW()),
('Double Cross', 'Crime', 'Hindi', 'Bollywood', '2K', 149, 'After a heist in Kolkata goes sideways, Rudra Rana has forty-eight hours to recover what was lost before Kabir Ahluwalia and the rest of the crew turn on each other.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Double%20Cross', '2026-12-17', 1, NOW()),
('Fracture Reborn', 'Sci-Fi', 'English', 'Hollywood', 'IMAX', 151, 'Marcus Sutton wakes up in a Boston that remembers a different version of history, and must work with June Thorne to figure out which timeline is real before the correction finishes erasing them both.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Fracture%20Reborn', '2027-03-24', 1, NOW()),
('Moonlit', 'Animation', 'Urdu', 'Bollywood', 'HD', 151, 'When the lights of Chandigarh start disappearing one by one, a curious young inventor named Diya Ahluwalia teams up with Dev Bhatt to find out who, or what, is behind it.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Moonlit', '2027-04-09', 1, NOW()),
('Sparks of Seattle', 'Animation', 'English', 'Hollywood', 'HD', 122, 'In a vividly imagined version of Seattle, a small, determined creature named Grant Callahan sets out to save its shrinking home, with the reluctant help of a wandering wanderer voiced by the spirit of June Reyes.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Sparks%20of%20Seattle', '2027-07-11', 1, NOW()),
('Blackout', 'Action', 'Urdu', 'Bollywood', 'HD', 156, 'Zara Ahluwalia, a disgraced officer exiled to the edges of Chandigarh, is pulled back into action when Riya Malhotra is taken hostage during a botched raid. What starts as a rescue turns into a reckoning with the syndicate Zara Ahluwalia once worked for.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Blackout', '2027-05-25', 1, NOW()),
('Dead Air Unbound', 'Horror', 'English', 'Hollywood', 'IMAX', 150, 'Wesley Faulkner and Talia Marsh take a caretaker job at an isolated property outside San Diego, only to discover the previous caretakers never actually left.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Dead%20Air%20Unbound', '2026-07-11', 1, NOW()),
('False Trail Goa', 'Thriller', 'Hindi', 'Bollywood', 'HD', 98, 'A routine assignment turns dangerous when Kabir Rana uncovers evidence that implicates Anaya Mehra, forcing a race across Goa before the truth gets buried for good.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=False%20Trail%20Goa', '2027-03-28', 1, NOW()),
('Wild Unbound', 'Adventure', 'English', 'Hollywood', '4K', 143, 'When an old map surfaces in Miami, Marcus Harmon and Mia Quinn set off on a journey neither expected, chasing a legend that keeps rewriting itself the closer they get to the truth.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Wild%20Unbound', '2027-05-27', 1, NOW()),
('The Wedding Unbound', 'Comedy', 'Hindi', 'Bollywood', '2K', 98, 'When Rohan Ahluwalia accidentally becomes the face of a failing local business in Hyderabad, chaos, and an unlikely friendship with Arjun Rana, follow at every turn.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=The%20Wedding%20Unbound', '2026-01-20', 1, NOW()),
('Lost Unbound', 'Adventure', 'English', 'Hollywood', '2K', 142, 'When an old map surfaces in New Orleans, Jack Thorne and Jack Beckett set off on a journey neither expected, chasing a legend that keeps rewriting itself the closer they get to the truth.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Lost%20Unbound', '2026-03-10', 1, NOW()),
('Beyond Pune', 'Adventure', 'Urdu', 'Bollywood', '4K', 108, 'A weathered guide named Kavya Chatterjee agrees to lead Arjun Sinha across the forgotten trails beyond Pune in search of a relic that vanished generations ago, unaware that the journey will cost them everything they thought they knew about home.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Beyond%20Pune', '2026-10-26', 1, NOW()),
('Signal Rising', 'Sci-Fi', 'English', 'Hollywood', 'IMAX', 96, 'Mia Callahan wakes up in a New Orleans that remembers a different version of history, and must work with June Whitfield to figure out which timeline is real before the correction finishes erasing them both.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Signal%20Rising', '2027-02-14', 1, NOW()),
('Quiet', 'Romance', 'Urdu', 'Bollywood', 'IMAX', 163, 'Years after a breakup no one really explained, Naina Sethi runs into Aryan Rana again in Lucknow, and old feelings resurface at exactly the wrong, and maybe the right, time.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Quiet', '2027-07-27', 1, NOW()),
('Two Hearts Revisited', 'Romance', 'English', 'Hollywood', 'IMAX', 154, 'Roman Quinn and Grant Faulkner meet by accident on a rainy evening in Denver, and what begins as a passing conversation slowly turns into the kind of love neither of them was looking for, or ready to walk away from.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Two%20Hearts%20Revisited', '2027-01-16', 1, NOW()),
('Silent Revisited', 'Action', 'Urdu', 'Bollywood', '2K', 96, 'Aditya Chauhan, a disgraced officer exiled to the edges of Amritsar, is pulled back into action when Diya Rathore is taken hostage during a botched raid. What starts as a rescue turns into a reckoning with the syndicate Aditya Chauhan once worked for.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Silent%20Revisited', '2026-04-24', 1, NOW()),
('Beyond', 'Adventure', 'English', 'Hollywood', '2K', 132, 'A weathered guide named Talia Beckett agrees to lead June Cross across the forgotten trails beyond Denver in search of a relic that vanished generations ago, unaware that the journey will cost them everything they thought they knew about home.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=Beyond', '2027-12-08', 1, NOW()),
('The Job Goa', 'Crime', 'Urdu', 'Bollywood', '4K', 129, 'Detective Simran Sethi is pulled back to Goa to close a case that was never really closed, only to find Karan Bajwa at the center of it all along.', NULL, 'https://placehold.co/500x750/11141c/e50914?font=montserrat&text=The%20Job%20Goa', '2027-04-04', 1, NOW());
