<?php
/* Shared header + sidebar for every admin panel page. */
require_once __DIR__ . '/../includes/functions.php';
requireAdmin();
$current = basename($_SERVER['PHP_SELF']);
?>
<!DOCTYPE html>
<html lang="en">
<head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Admin Cockpit - CineVerse</title> <link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Outfit:wght@400;500;600;700;800&family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet"> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css"> <link rel="stylesheet" href="../assets/css/style.css?v=<?php echo file_exists(__DIR__.'/../assets/css/style.css') ? filemtime(__DIR__.'/../assets/css/style.css') : time(); ?>"> <script> (function () {
            try {
                if (localStorage.getItem('theme') === 'light') {
                    document.documentElement.classList.add('light-theme');
                }
            } catch (e) {}
        })(); </script>
</head>
<body> <header class="navbar navbar-expand-lg"> <div class="nav-inner container-fluid"> <div class="nav-left"> <a href="dashboard.php" class="brand"> <div class="brand-logo-wrap"> <img src="../assets/img/logo.svg?v=<?php echo file_exists(__DIR__.'/../assets/img/logo.svg') ? filemtime(__DIR__.'/../assets/img/logo.svg') : time(); ?>" alt="CineVerse Admin" class="brand-logo"> </div> <div class="brand-text"> <span class="bt-main">Movie Booking</span> <span class="bt-sub">Cockpit <em>Admin</em></span> </div> </a> <button type="button" class="theme-toggle" id="themeToggleBtn" aria-label="Toggle light/dark theme" title="Toggle theme"> <span class="theme-label theme-label-dark">Dark</span> <span class="theme-label theme-label-light">Light</span> </button> </div> <nav class="navbar-collapse" style="flex-grow:0;display:flex;align-items:center;gap:14px;"> <span class="user-pill"> <span class="user-avatar-wrap"><?php echo clean(mb_strtoupper(mb_substr($_SESSION['admin_name'], 0, 1))); ?></span> <span><?php echo clean($_SESSION['admin_name']); ?></span> </span> <a href="logout.php" style="color:var(--neon-pink);font-weight:700;font-size:13.5px;">Logout</a> </nav> </div>
</header> <div style="display:flex;min-height:calc(100vh - 72px);"> <div class="admin-sidebar" style="width:240px;flex-shrink:0;"> <a href="dashboard.php" <?php echo $current==='dashboard.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Dashboard</a> <a href="movies.php" <?php echo $current==='movies.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Movies</a> <a href="theaters.php" <?php echo $current==='theaters.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Theaters</a> <a href="shows.php" <?php echo $current==='shows.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Shows & Rates</a> <a href="screens.php" <?php echo ($current==='screens.php'||$current==='screen_seats.php')?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Screens & Seats</a> <a href="bookings.php" <?php echo $current==='bookings.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Bookings</a> <a href="reviews.php" <?php echo $current==='reviews.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Reviews</a> <a href="coupons.php" <?php echo $current==='coupons.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Coupons</a> <a href="seed_data.php" <?php echo $current==='seed_data.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Bulk Setup</a> <a href="users.php" <?php echo $current==='users.php'?'style="color:var(--neon-cyan);background:rgba(0,242,254,0.1);"':''; ?>> Users</a> <a href="../index.php" style="margin-top:20px;border-top:1px solid var(--border-glass);padding-top:14px;color:var(--neon-amber);"> View Main Site</a> </div> <div class="admin-content" style="flex:1;">
